name: Resolve-IT CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/common.in
        pip install -r requirements/dev.in

    - name: Setting up Resolve-IT
      run: |
        python3 setup.py install

    - name: Running tests
      run: |
        python3 tests/test_app.py
        python3 tests/test_fetch_results.py
        python3 tests/test_resolveit.py
        python3 tests/test_rparser.py        
