name: Resolve-IT CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9   # It is better to not change this as this may cause tests to
                                # fail since exception errors differ on each python version.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/common.in
        pip install -r requirements/dev.in

    - name: Setting up Resolve-IT
      run: |
        python setup.py install

    - name: Running tests
      run: |
        coverage run -m unittest discover tests

    - name: Checking code coverage
      run: |
        python tools/check_coverage
